### ISSUE TITLE
"no more follow button. scrolling down"

### ISSUE THREAD

**Issue by jonathanfilbert** [pbradaric/instagram-unfollow-script#1]
It it supposed to say that?

I've pasted the code in the console while in the following tab of my Insta

**Comment by pbradaric** [comment]
Huh, I just got notified about the opened issue - but it seems you've posted this 2 months ago. Strange.
Anyway, the issue you're (were) experiencing is one of the issues listed in **Possible Issues** section in the README. So, the script is trying to find any **Following** buttons (line 17) but it fails - because the selector is probably unique to my case (line 5). So, in order to make this work you'll have to open up the Developer's Console, inspect the DOM and find out what's the class name for your **Following** button(s) - then update the selector in `fwButtonSelector` variable (line 5).
